name: Docs
on: [push, release]

jobs:
  notebooks:
    name: "Build the notebooks for the docs"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
   
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install black
          pip install --upgrade numpy ipython jupyter cython astropy
          pip install jupytext jupyterthemes
          #pip3 install git+https://github.com/threeML/astromodels.git@dev#egg=astromodels
          #pip3 install git+https://github.com/threeML/threeML.git@dev#egg=threeML
          
          python setup.py develop
          
          
      - name: Execute the notebooks
        shell: bash -l {0}
        run: |

          jupytext --to ipynb --pipe black --execute docs/md/*.md
          mv docs/md/*.ipynb docs/notebooks
          
      - uses: actions/upload-artifact@v2
        with:
          name: notebooks-for-${{ github.sha }}
          path: docs/notebooks


  api_doc:
    name: "Create the API stubs"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8        

      - name: Build the API doc
        run: |

          brew install c-blosc
          brew install hdf5


          pip3 install cython
          pip3 install numpy scipy numba astropy
          #pip3 install git+https://github.com/threeML/astromodels.git@dev#egg=astromodels
          #pip3 install git+https://github.com/threeML/threeML.git@dev#egg=threeML
          python setup.py develop


          
          brew install sphinx-doc pandoc

          pip3 install wheel
          pip3 install mock recommonmark
          pip3 install sphinx_rtd_theme
          pip3 install -U sphinx nbsphinx sphinx-gallery
          
          
          sphinx-apidoc -f -o docs/api/ rball


      - uses: actions/upload-artifact@v2
        with:
          name: api-stubs-for-${{ github.sha }}
          path: docs/api

          
  build_docs:
    name: "Build the Documentation"
    runs-on: macos-latest
    needs: [notebooks, api_doc]
    steps:


      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8        

      - name: Install package
        run: |

          brew install c-blosc
          brew install hdf5


          pip3 install numpy scipy numba astropy
          #pip3 install git+https://github.com/threeML/astromodels.git@dev#egg=astromodels
          #pip3 install git+https://github.com/threeML/threeML.git@dev#egg=threeML
          brew install sphinx-doc pandoc

          pip3 install wheel
          pip3 install mock recommonmark
          pip3 install sphinx_rtd_theme
          pip3 install -U sphinx nbsphinx sphinx-gallery
          
          python3 setup.py develop

          rm -rf docs/md/*
          
      - uses: actions/download-artifact@master
        with:
          name: notebooks-for-${{ github.sha }}
          path: docs/notebooks


      - uses: actions/download-artifact@master
        with:
          name: api-stubs-for-${{ github.sha }}
          path: docs/notebooks/api

      
      - name: Build and Commit
        uses: sphinx-notes/pages@master
        with:
          documentation_path: docs
        
      - name: Push changes
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages


